substitutions:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  flash_size: 4MB

# Board specific entities
# Output that blinks the LED
output:
  - platform: template
    id: status_output
    type: binary
    write_action:
      - if:
          condition:
            lambda: return (state);
          then:
            - light.turn_on:
                id: led
                brightness: 70%
                red: 100%
                green: 0%
                blue: 0%
          else:
            - light.turn_off: led

light:
  # Enable status LED
  - platform: status_led
    output: status_output
    name: "Status Led"
    entity_category: diagnostic

  #G35=RGB WS2812C-2020
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO4
    num_leds: 1
    chipset: SK6812
    id: led
    name: "Led"
    entity_category: diagnostic
    restore_mode: ALWAYS_OFF

#G41=Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: GPIO3
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
